apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ticketing
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ticketing-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketing-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-time-zone=+09:00