apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  namespace: ticketing
data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: ticketing
  REDIS_HOST: redis-service
  KAFKA_SERVERS: kafka-service:9092
  EVENT_SERVICE_HOST: localhost